In [47]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [5]:
def add_slucky_variables(A, b):
    
    m, n = A.shape
    slack_vars = np.eye(m,m+1)
    A_slack = np.hstack((A, slack_vars,b.reshape(-1,1)))
    return A_slack

In [105]:
def simplex(x):
    x = x.astype(float)
    while True:
        min_z = np.min(x[-1, :-1])
        if min_z >= 0:
            break  # Optimal reached
        index_z = np.argmin(x[-1, :-1])
        selected_col = x[:, index_z]
        with np.errstate(divide='ignore', invalid='ignore'):
            ratios = np.where(selected_col > 0, x[:, -1] / selected_col, np.inf)
        ratios = ratios[:-1]  # Exclude last row (objective)
        if np.all(ratios == np.inf):
            raise Exception("Unbounded solution")
        index_r = np.argmin(ratios)
        pivot = x[index_r, index_z]
        x[index_r, :] = x[index_r, :] / pivot
        for i in range(x.shape[0]):
            if i != index_r:
                x[i, :] = x[i, :] - x[i, index_z] * x[index_r, :]
        x = np.round(x, 6)
    return x

In [106]:
d = np.array([[1, 1], [4, 1],[-20,-10]])
b = np.array([40, 100,0])
print("Simplex module loaded.")
x = add_slucky_variables(d, b)
x

Simplex module loaded.


array([[  1.,   1.,   1.,   0.,   0.,   0.,  40.],
       [  4.,   1.,   0.,   1.,   0.,   0., 100.],
       [-20., -10.,   0.,   0.,   1.,   0.,   0.]])

In [110]:
for row in simplex(x):
    print(row)

[ 0.        1.        1.333333 -0.333333  0.        0.       20.      ]
[ 1.        0.       -0.333333  0.333333  0.        0.       20.      ]
[  0.         0.         6.666667   3.333333   1.         0.
 600.      ]


In [108]:
1/4

0.25

In [113]:
import numpy as np

tensor = np.array([[[7, 8],
                    [2, 5]],
                   [[3, 6],
                    [1, 4]]])
print(tensor)
index_min = np.argmin(tensor, axis=1)
print(index_min)


[[[7 8]
  [2 5]]

 [[3 6]
  [1 4]]]
[[1 1]
 [1 1]]
