In [35]:
import numpy as np

X = np.random.randn(2,3)
w = np.random.randn(3,2)
b = np.random.randn(2)


In [36]:
def perc(X,w,b):
    return X @ w + b

In [37]:
z1 = perc(X,w,b)
z1

array([[-2.3987602 , -1.12334613],
       [ 0.8584809 , -0.83070073]])

In [39]:
def ReLU(X):
    return np.maximum(0,X)
ReLU(z1)

array([[0.       , 0.       ],
       [0.8584809, 0.       ]])

In [43]:
def sigmoid(X):
    return 1/(1+np.exp(-X))
sigmoid(z1)

array([[0.08326729, 0.24539114],
       [0.70234317, 0.30349693]])